services:
  - type: web
    name: ai-image-generator
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        value: